
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAIL = 'SUBMIT_FAIL';

export const GET_GAME_ENTRYED_LIST_SUCCESS  = 'GET_GAME_ENTRYED_LIST_SUCCESS';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_DETAIL_SUCCESS = 'GET_GAME_DETAIL_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
