
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const POST_LOGIN_SUCCESS= 'POST_LOGIN_SUCCESS';
export const POST_REGISTER_SUCCESS= 'POST_REGISTER_SUCCESS';
export const PUT_USERINFO_SUCCESS= 'PUT_USERINFO_SUCCESS';
export const SUBMIT_FAIL = 'SUBMIT_FAIL';

export const GET_GAME_ENTRYED_LIST_SUCCESS  = 'GET_GAME_ENTRYED_LIST_SUCCESS';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_DETAIL_SUCCESS = 'GET_GAME_DETAIL_SUCCESS';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_COLLEGES_SUCCESS = 'GET_COLLEGES_SUCCESS';
export const GET_INSTITUTES_SUCCESS = 'GET_INSTITUTES_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';

export const SET_ENTRY_STEP = 'SET_ENTRY_STEP';

export const CLEAR_INSTITUTES = 'CLEAR_INSTITUTES';
